Jethro sammarcus
aksht94/UdacityOpenSource pull request #181
Opened 2019-08-20 23:20 UTC by Jethro-Sammarcus

Final files for project showcase

2019-08-20 23:42 UTC, kkech submitted a review, later dismissed
Hi @Jethro-Sammarcus ,

All the files have to be under your directory.

2019-08-21 03:46 UTC, Jethro-Sammarcus commented
Hi @kkech ,

I have deleted the other files I sent. Unfortunately, the training data was deleted from the Jethro Sam-Marcus folder by my error. Should I re-upload it? This will enable udacity test my submitted code.

2019-08-21 14:04 UTC, ZSoumia approved these changes

2019-08-21 14:11 UTC, ZSoumia requested changes
Please remove the last file as it's duplicate and all your files should be under Jethro-Sammarcus folder

2019-08-21 14:22 UTC, ZSoumia approved these changes

2019-08-21 14:23 UTC, merged